### PR TITLE
Draft types

### PR DESCRIPTION
**Pull request by sgnurf**
The end of the season is close and with it comes matches with format different than the 2bans/2picks we are used too.
I have added a dropdown list allowing users to select which kind of match they are playing upon creating a room.
Different match layouts (draft_type in the code) are configured in (draft/draft_types.json) for flexibility. For now using a different draft_type only changes the number of bans and picks to be done during the drafting.

### CODE REVIEW

**Comment by bradbeattie** [comment]
Thanks for the effort that goes into this. It's been quite helpful during the tournament!

**Comment by ben-schwartz** [comment]
Haha, I was _LITERALLY_ going to work on this tonight, but now you've saved me the effort.  I'll review the code after work today and merge.  Thanks for the contribution!

**Comment by sgnurf** [comment]
hehe, first time doing anything real with Python though. Be nice :).

**Comment by bradbeattie** [comment]
It might be worth running the code through pyflakes/pep8 to ensure style compliance. Seems pedantic at first, but consistent style really helps keep things understandable down the road.

**Comment by ben-schwartz** [comment]
@bradbeattie yeah agreed.  IntelliJ (my IDE of choice) will highlight any PEP8 errors, so it should _mostly_ be good from that perspective.  There are a few style things in @sgnurf's code, but they're so minor, I'll just fix them myself instead of closing the request :).  Thanks again sgnurf and I hope to get this deployed later tonight.

**Comment by ben-schwartz** [comment]
Oh, @sgnurf is there any social network site or anything you want me to link to when I credit you?

**Comment by sgnurf** [comment]
No problem, my pleasure.

I tried to follow the same coding style but yeah I surely missed stuff, I was more focused on understanding Python. Before clicking "fork" this morning the only thing I knew about it was that indentation matters for blocks... 

@ben-schwartz  nope, no social network, thank you

**Comment by bradbeattie** [comment]
@sgnurf http://learnpythonthehardway.org/book/ is a decent dive into details if you're new to the language. I found learning Python a lot more intuitive than my previous primary languages.

**Comment by sgnurf** [comment]
@bradbeattie Nice, thank you !

**Comment by ben-schwartz** [comment]
HAHA i just noticed I've been commenting on this as my work git-hub account instead of as LtHummus...whoops :D 

(Also, i've been teaching an intro to programming in Python on my stream, but that's more targeted towards folks that have never written code)

**Comment by sgnurf** [comment]
@ben-schwartz  I know about it, but yeah it did not feel like I was part of the targeted audience. The fact that it starts at something like 4am in my TZ adds to the feeling :D

**Pull request merged**
